const projects = [
    {
    num: "01",
    category: "Machine Learning, Deep Learning, Data Analytics, Social Engineering",
    title: "Evaluation of phishing detection methods",
    description: "Implementation and evaluation of various state-of-the-art phishing detection methods like blacklist, machine learning, deep learning and llm based on a realistic data set to examine its performance in real-world scenarios.",
    stack: [{ name: "Keras" }, { name: "scikit-learn" }, { name: "python" }, { name: "Jupyter Notebook"}, { name: "Google Safe Browsing API"}, { name: "ChatGPT" }],
    image: "/assets/projects/phishing.png",
    live: "",
    github: "https://github.com/neverchange95/phishing-detection",
  },
  {
    num: "02",
    category: "Fullstack, Cloud native development",
    title: "Supermarket Scout",
    description: "Cloud-native study project implementing microservices to provide backend services within a Kubernetes cluster for a web application. The application enables users to search for product prices from nearby supermarkets within a city.",
    stack: [{ name: "Spring Boot" }, { name: "PostgreSQL" }, { name: "python" }, { name: "Next.js" }, { name: "Tailwind CSS" }, { name: "Docker" }, { name: "Kubernetes/Helm" }, { name: "Github Actions" }],
    image: "/assets/projects/supermarket-scout.png",
    live: "",
    github: "https://github.com/neverchange95/supermarket-scout",
  },
  {
    num: "03",
    category: "Fullstack, Network (BGP) Security",
    title: "bgp-routing-looking-glass",
    description: "Study project that provides a Looking Glass for analyzing internet traffic from data centers and visualizing potential anomalies.",
    stack: [{ name: "React" }, { name: "CSS3" }, { name: "python" }, { name: "Apache Spark" }, { name: "BGP" }],
    image: "/assets/projects/bgp.png",
    live: "",
    github: "https://github.com/neverchange95/bgp-routing-looking-glass",
  },
  {
    num: "04",
    category: "Fullstack, Authentication Security",
    title: "webauthn",
    description: "Example application that walks through the registration and authentication phases of the WebAuthn standard, visualizing the exchanged and generated values, to examine practical behavior and operational limitations.",
    stack: [{ name: "React.js" }, { name: "Spring Boot" }, { name: "FIDO 2" }, { name: "WebAuthn" }],
    image: "/assets/projects/webauthn.png",
    live: "",
    github: "https://github.com/neverchange95/WebAuthnDemo",
  },
  {
    num: "05",
    category: "Frontend, Portfolio",
    title: "portfolio 1",
    description: "My portfolio application.",
    stack: [{ name: "Next.js" }],
    image: "/assets/projects/portfolio_new.png",
    live: "http://michael-kuechenmeister.de/",
    github: "https://github.com/neverchange95/portfolio",
  },
  {
    num: "06",
    category: "Frontend, Portfolio",
    title: "portfolio 2",
    description: "An older portfolio application.",
    stack: [{ name: "HTML5" }, { name: "CSS3" }, { name: "JavaScript" }],
    image: "/assets/projects/portfolio.png",
    live: "",
    github: "https://github.com/neverchange95/MyWebsite",
  },
  {
    num: "07",
    category: "Frontend, Searching Algorithms",
    title: "dfs/bfs",
    description: "A visualization of a depth-first and breadth-first search algorithm.",
    stack: [{ name: "HTML5" }, { name: "CSS3" }, { name: "JavaScript" }],
    image: "/assets/projects/dfs-bfs.png",
    live: "",
    github: "https://github.com/neverchange95/VisualSearch",
  },
  {
    num: "08",
    category: "UI/UX-design",
    title: "smart-home",
    description: "Design concept for a smart home frontend application.",
    stack: [{ name: "Figma" }],
    image: "/assets/projects/smart-home.jpg",
    live: "",
    github: "https://github.com/neverchange95/smart-home",
  },
  {
    num: "09",
    category: "Android Application",
    title: "dfs/bfs",
    description: "A todo application for android smartphones.",
    stack: [{ name: "Java" }, { name: "Android Studio" }, { name: "SQL" }],
    image: "/assets/projects/todo.jpg",
    live: "",
    github: "https://github.com/neverchange95/ToDoApp",
  },
  {
    num: "10",
    category: "Malware",
    title: "rootkit",
    description: "A linux kernel mode rootkit designed to hide process IDs (PIDs), along with a keylogger that remains concealed from the user through the rootkit.",
    stack: [{ name: "C" }, { name: "Linux Kernel" }],
    image: "/assets/projects/rootkit.png",
    live: "",
    github: "https://github.com/neverchange95/Rootkit",
  },
  {
    num: "11",
    category: "Java Application",
    title: "dronesimulation",
    description: "A student project that implements a realistic drone simulation and visualizes it via a GUI.",
    stack: [{ name: "Java" }, { name: "Maven" }],
    image: "/assets/projects/drone.png",
    live: "",
    github: "https://github.com/neverchange95/Drohnensimulation",
  },
];

export default projects;